version: '3.9'

services:
  db:
    image: postgres:12.8-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - '5432'
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata'
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PGPASS: 1234
        PGUSER: postgres
        RACK_ENV: production
        RAILS_ENV: production
        HOST: 'http://169.59.160.70'
        PORT: ''
    ports:
      - "80:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    links:
      - db

volumes:
  db-data:
